from __future__ import annotations

from typing import Dict, List

TARGET_COLUMNS: List[str] = [
    "Patient_ID",
    "平均血小板体积",
    "直接胆红素",
    "间接胆红素",
    "白蛋白",
    "尿素/肌酐比值",
    "D-二聚体",
    "钾离子",
    "钠离子",
    "血红蛋白",
    "γ-谷氨酰转移酶",
    "氯离子",
    "嗜碱性粒细胞百分比",
    "中性粒细胞计数",
    "淋巴细胞计数",
    "嗜碱性粒细胞计数",
    "红细胞计数",
    "平均血红蛋白量",
    "平均血红蛋白浓度",
    "血小板计数",
    "血小板分布宽度",
    "超敏C反应蛋白",
    "白球比值",
    "葡萄糖",
    "白细胞计数",
    "淋巴细胞百分比",
    "总钙",
    "淀粉酶",
    "平均红细胞体积",
    "中性粒细胞百分比",
    "单核细胞百分比",
    "嗜酸性粒细胞百分比",
    "单核细胞计数",
    "嗜酸性粒细胞计数",
    "尿素",
    "肌酐",
    "红细胞压积",
    "丙氨酸氨基转移酶",
    "天门冬氨酸氨基转移酶",
    "碱性磷酸酶",
    "总胆红素",
    "总蛋白",
    "血小板压积",
    "AST/ALT比值",
    "球蛋白",
]


INDICATOR_SYNONYMS: Dict[str, List[str]] = {
    "Patient_ID": ["病历号", "住院号", "门诊号", "住院号码", "Patient ID", "ID", "编号"],
    "平均血小板体积": ["MPV", "Mean Platelet Volume", "平均血小板体积(测)", "平均血小板体积(计算)"],
    "直接胆红素": ["Direct Bilirubin", "DBIL", "直接总胆红素"],
    "间接胆红素": ["Indirect Bilirubin", "IBIL"],
    "白蛋白": ["Albumin", "ALB"],
    "尿素/肌酐比值": ["Urea/Creatinine Ratio", "BUN/Cr", "尿素肌酐比值"],
    "D-二聚体": ["D-Dimer", "DDIM", "D二聚体"],
    "钾离子": ["Potassium", "K+", "血钾"],
    "钠离子": ["Sodium", "Na+", "血钠"],
    "血红蛋白": ["Hemoglobin", "Hb", "血红蛋白测定"],
    "γ-谷氨酰转移酶": ["γ-GT", "GGT", "谷氨酰转肽酶", "谷酰转肽酶"],
    "氯离子": ["Chloride", "Cl-", "血氯"],
    "嗜碱性粒细胞百分比": ["Basophil Percentage", "Baso%", "Bas%", "嗜碱细胞比例"],
    "中性粒细胞计数": ["Neutrophil Count", "NE#", "中性粒细胞绝对值", "中性粒细胞绝对数"],
    "淋巴细胞计数": ["Lymphocyte Count", "LY#", "淋巴细胞绝对值", "淋巴细胞绝对数"],
    "嗜碱性粒细胞计数": ["Basophil Count", "BA#", "嗜碱细胞绝对值"],
    "红细胞计数": ["Red Blood Cell Count", "RBC"],
    "平均血红蛋白量": ["MCH", "平均红细胞血红蛋白量"],
    "平均血红蛋白浓度": ["MCHC", "平均红细胞血红蛋白浓度"],
    "血小板计数": ["Platelet Count", "PLT", "血小板数"],
    "血小板分布宽度": ["PDW", "血小板体积分布宽度"],
    "超敏C反应蛋白": ["hs-CRP", "高敏C反应蛋白", "高敏感C反应蛋白"],
    "白球比值": ["Albumin/Globulin Ratio", "A/G", "白/球比值"],
    "葡萄糖": ["Glucose", "GLU", "血糖"],
    "白细胞计数": ["WBC", "白细胞数", "White Blood Cell Count"],
    "淋巴细胞百分比": ["Lymphocyte Percentage", "LY%", "淋巴细胞比率"],
    "总钙": ["Total Calcium", "Ca", "总钙含量"],
    "淀粉酶": ["Amylase", "AMY"],
    "平均红细胞体积": ["MCV", "平均红细胞体积(测)"],
    "中性粒细胞百分比": ["Neutrophil Percentage", "NE%", "中性粒细胞比率"],
    "单核细胞百分比": ["Monocyte Percentage", "MO%", "单核细胞比率"],
    "嗜酸性粒细胞百分比": ["Eosinophil Percentage", "EO%", "嗜酸细胞比率"],
    "单核细胞计数": ["Monocyte Count", "MO#", "单核细胞绝对值"],
    "嗜酸性粒细胞计数": ["Eosinophil Count", "EO#", "嗜酸细胞绝对值"],
    "尿素": ["Urea", "BUN", "血尿素氮"],
    "肌酐": ["Creatinine", "Cr", "肌酐测定"],
    "红细胞压积": ["Hematocrit", "HCT"],
    "丙氨酸氨基转移酶": ["ALT", "谷丙转氨酶", "丙氨酸转氨酶"],
    "天门冬氨酸氨基转移酶": ["AST", "谷草转氨酶", "天门冬氨酸转氨酶"],
    "碱性磷酸酶": ["ALP", "碱性磷酸酶活性"],
    "总胆红素": ["Total Bilirubin", "TBIL", "总胆红素测定"],
    "总蛋白": ["Total Protein", "TP"],
    "血小板压积": ["PCT", "血小板比积"],
    "AST/ALT比值": ["AST/ALT Ratio", "De Ritis ratio", "AST:ALT"],
    "球蛋白": ["Globulin", "GLB"],
}

